package asf.dungeon.model;

public enum ModelId {
        Archer,
        Berzerker,
        Cerberus,
        Diablous,
        FemaleMage,
        Knight,
        Mage,
        Priest,
        Skeleton,
        Goblin,
        RockMonster,
        CeramicPitcher,
        Crate,
        Barrel,
        Chest,
        Fountain,
        Torch,
        SignPost,
        SpikeTrap,
        Boulder,
        Potion,
        Scroll,
        Book,
        Key,
        Key2,
        Key3,
        SwordLarge,
        Sword_01,
        BowLarge,
        Bow_01;

}
